Repository INTECS-ITFAC/intecs_webapp_front-end, pull requests merged in 2020-04, with the labels that each got.

#25 update readme
  README.md
Labels: documentation

#36 minor change
  src/modules/event/Event.tsx
Labels: bug

#37 Added a navigation bar and updated README.md
  README.md
  src/components/navbar/Navbar.tsx
  src/index.tsx
Labels: enhancement
